[target.x86_64-pc-windows-msvc]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-musl-gcc"
ar = "x86_64-linux-musl-ar"

[env]
# Windows cross-compilation
CC_x86_64_pc_windows_msvc = "x86_64-w64-mingw32-gcc"
CXX_x86_64_pc_windows_msvc = "x86_64-w64-mingw32-g++"
AR_x86_64_pc_windows_msvc = "x86_64-w64-mingw32-ar"

# Linux cross-compilation
CC_x86_64_unknown_linux_gnu = "x86_64-linux-musl-gcc"
CXX_x86_64_unknown_linux_gnu = "x86_64-linux-musl-g++"
AR_x86_64_unknown_linux_gnu = "x86_64-linux-musl-ar"
