// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Skanyxx.Module.Memory.Data;

#nullable disable

namespace Skanyxx.Module.Memory.Data.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    [Migration("20261006150935_StudioOwnership")]
    partial class StudioOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skanyxx.Module.Memory.Domain.AgentGrant", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.Property<string>("Scope")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("scope");

                    b.Property<bool>("CanSearch")
                        .HasColumnType("boolean")
                        .HasColumnName("can_search");

                    b.Property<bool>("CanUpsert")
                        .HasColumnType("boolean")
                        .HasColumnName("can_upsert");

                    b.HasKey("AgentId", "Scope");

                    b.ToTable("memory_agent_grants", null, t =>
                        {
                            t.HasCheckConstraint("ck_memory_agent_grants_agent", "agent_id ~ '^[a-z0-9][a-z0-9._@-]{0,127}$'");

                            t.HasCheckConstraint("ck_memory_agent_grants_scope", "scope IN ('personal', 'company') OR scope ~ '^(team|department):[a-z0-9][a-z0-9._@-]{0,127}$'");
                        });
                });

            modelBuilder.Entity("Skanyxx.Module.Memory.Domain.AgentSecret", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.Property<bool>("ActsForUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("acts_for_users");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("AgentId");

                    b.HasIndex("SecretHash")
                        .IsUnique();

                    b.ToTable("memory_agent_secrets", null, t =>
                        {
                            t.HasCheckConstraint("ck_memory_agent_secrets_agent", "agent_id ~ '^[a-z0-9][a-z0-9._@-]{0,127}$'");

                            t.HasCheckConstraint("ck_memory_agent_secrets_hash", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Skanyxx.Module.Memory.Domain.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("body");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<long?>("LiftedFromId")
                        .HasColumnType("bigint")
                        .HasColumnName("lifted_from");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("scope");

                    b.Property<NpgsqlTsVector>("Search")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("setweight(to_tsvector('english'::regconfig, key), 'A') || setweight(to_tsvector('english'::regconfig, replace(key, '-', ' ')), 'A') || setweight(to_tsvector('english'::regconfig, what), 'A') || setweight(to_tsvector('english'::regconfig, why), 'B')", true);

                    b.Property<string>("Source")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("What")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("what");

                    b.Property<string>("Who")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("who");

                    b.Property<string>("Why")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("why");

                    b.HasKey("Id");

                    b.HasIndex("LiftedFromId");

                    b.HasIndex("Search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.HasIndex("Scope", "Key")
                        .IsUnique();

                    b.ToTable("memory_cards", null, t =>
                        {
                            t.HasCheckConstraint("ck_memory_cards_key", "key ~ '^[a-z0-9][a-z0-9-]{0,79}$'");

                            t.HasCheckConstraint("ck_memory_cards_scope", "scope = 'company' OR scope ~ '^(personal|team|department):[a-z0-9][a-z0-9._@-]{0,127}$'");

                            t.HasCheckConstraint("ck_memory_cards_status", "status IN ('candidate', 'published', 'stale')");

                            t.HasCheckConstraint("ck_memory_cards_type", "type IN ('decision', 'fact', 'procedure', 'open')");

                            t.HasCheckConstraint("ck_memory_cards_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Skanyxx.Module.Memory.Domain.StudioAgent", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("DeployedFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("deployed_fingerprint");

                    b.Property<bool>("Suspended")
                        .HasColumnType("boolean")
                        .HasColumnName("suspended");

                    b.HasKey("AgentId");

                    b.ToTable("memory_studio_agents", null, t =>
                        {
                            t.HasCheckConstraint("ck_memory_studio_agents_agent", "agent_id ~ '^[a-z0-9][a-z0-9._@-]{0,127}$'");
                        });
                });

            modelBuilder.Entity("Skanyxx.Module.Memory.Domain.StudioRepo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("recorded_by");

                    b.Property<string>("RepoCreatedAt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("repo_created_at");

                    b.Property<long>("RepoId")
                        .HasColumnType("bigint")
                        .HasColumnName("repo_id");

                    b.HasKey("Id");

                    b.ToTable("memory_studio_repo", null, t =>
                        {
                            t.HasCheckConstraint("ck_memory_studio_repo_single", "id = 1");
                        });
                });

            modelBuilder.Entity("Skanyxx.Module.Memory.Domain.Card", b =>
                {
                    b.HasOne("Skanyxx.Module.Memory.Domain.Card", null)
                        .WithMany()
                        .HasForeignKey("LiftedFromId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
